name: pixel_adventure
version: 1.1.1
publish_to: https://onepub.dev/api/usavvuhnof/
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flame: ^1.8.2
  flame_tiled: ^1.11.0
  flame_audio: ^2.0.5
  flutter: 
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/audio/
    - assets/tiles/
    - assets/images/Background/
    - assets/images/Terrain/
    - assets/images/HUD/
    - assets/images/Traps/Saw/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Items/Fruits/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Enemies/Chicken/
  uses-material-design: true
homepage: https://github.com/EzCompostr-App/tpixel_adventure
repository: https://github.com/EzCompostr-App/tpixel_adventure
